trigger:
- none

pool:
  name: <poolName>

variables:

  - name: workspace
    ${{ if contains(variables['Build.DefinitionName'], 'Dev UKS') }}:
      value: dv-uks
    ${{ elseif contains(variables['Build.DefinitionName'], 'Dev UKW') }}:
          value: dv-ukw
    ${{ elseif contains(variables['Build.DefinitionName'], 'Pre-Prod UKS') }}:
      value: pp-uks
    ${{ elseif contains(variables['Build.DefinitionName'], 'Prod UKS') }}:
      value: pa-uks
    ${{ else }}:
      value: default


stages:

  - stage: WORKSPACE
    displayName: WORKSPACE
    jobs:
    - job: 'initiating_workspace'
      steps:
      - powershell: |
          Write-Host "A pipeline named '$(Build.DefinitionName)' means a workspace called '$(workspace)'"
        displayName: 'Display Workspace Output'

  - stage: CHECK
    displayName: CHECK
    dependsOn:
    - WORKSPACE
    condition: |
      and(succeeded(), ne(variables['workspace'], 'default'))
    jobs:
    - job: 'Cancel_Default_Workspace'
      displayName: 'Cancel Default Workspace'
      steps:

      - powershell: |
          Write-Host "A pipeline named '$(Build.DefinitionName)' means a workspace called '$(workspace)'"
        displayName: 'Display Workspace/Environment Data'

  - stage: CANCEL
    dependsOn:
    - CHECK
    condition: eq(variables['workspace'], 'default')
    displayName: CANCEL
    jobs:
    - job: 'Default_Workspace_Located'
      displayName: 'Default Workspace Located'
      steps:

      - powershell: |
          Write-Host "The pipeline has exited as workspace is default"
        displayName: 'Display Stop Message'

      - powershell: |
          Set-Location terraform
          terraform output -raw output_resource_group
        displayName: 'Terraform Output RG Name'

  - stage: PLAN
    displayName: 'PLAN'
    dependsOn:
    - CHECK
    - WORKSPACE
    condition: and(succeeded(), ne(variables['workspace'], 'default'))
    jobs:
      - job: 'Plan'
        displayName: 'Terraform Plan'
        steps:

          - task: AzureCLI@3
            displayName: 'Terraform Init'
            inputs:
              connectionType: 'azureRM'
              azureSubscription: <ServiceConnection>
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              workingDirectory: 'terraform'
              inlineScript: |
                terraform init

          - task: AzureCLI@3
            displayName: 'Terraform Validate'
            inputs:
              connectionType: 'azureRM'
              azureSubscription: <ServiceConnection>
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              workingDirectory: 'terraform'
              inlineScript: |
                terraform validate

          - task: AzureCLI@3
            displayName: 'Initialize Workspace'
            inputs:
              connectionType: 'azureRM'
              azureSubscription: '<ServiceConnection>'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              workingDirectory: 'terraform'
              inlineScript: |
                powershell -NoProfile -ExecutionPolicy Bypass -File "environments/workspace.ps1" -workspaceName "$(workspace)"

          - task: AzureCLI@3
            displayName: 'Terraform Plan'
            inputs:
              connectionType: 'azureRM'
              azureSubscription: '<ServiceConnection>'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              workingDirectory: 'terraform'
              inlineScript: |
                terraform plan -out=tfplan

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'tfplan'
            displayName: 'Publish Plan and Cost Reports'
